# Generated by Django 5.2.4 on 2025-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_empresa_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetabloide',
            name='cor_fundo_alternada',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
    ]
