# Generated by Django 5.2.4 on 2025-08-21 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_auto_20250820_1544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetabloide',
            name='cor_fundo_linha',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatetabloide',
            name='cor_fundo_row',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de fundo principal'),
        ),
        migrations.AlterField(
            model_name='templatetabloide',
            name='cor_fundo_alternada',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Cor de fundo alternada'),
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
