# Generated by Django 5.2.4 on 2025-08-25 14:38

import relatorios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_remove_templatetabloide_cor_fundo_linha_empresa_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=10, validators=[relatorios.validators.validate_cep]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[relatorios.validators.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, validators=[relatorios.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[relatorios.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, validators=[relatorios.validators.validate_phone]),
        ),
    ]
