# Generated by Django 5.2.4 on 2025-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_alter_empresa_cep_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaprecoimportacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
