# Generated by Django 5.2.4 on 2025-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ie', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('dark_bg', models.CharField(default='#0b0c10', max_length=7)),
                ('dark_card', models.CharField(default='#12141a', max_length=7)),
                ('dark_text', models.CharField(default='#e6edf3', max_length=7)),
                ('dark_muted', models.CharField(default='#9aa4b2', max_length=7)),
                ('dark_brand', models.CharField(default='#7c3aed', max_length=7)),
                ('light_bg', models.CharField(default='#f7f7f8', max_length=7)),
                ('light_card', models.CharField(default='#ffffff', max_length=7)),
                ('light_text', models.CharField(default='#0b1220', max_length=7)),
                ('light_muted', models.CharField(default='#4b5563', max_length=7)),
                ('light_brand', models.CharField(default='#7c3aed', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuração de Tema',
                'verbose_name_plural': 'Configurações de Tema',
            },
        ),
    ]
